name: Build project
on: [push]
jobs:
  spm:
    name: Build & Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.0,name=iPhone X', 'platform=tvOS Simulator,OS=13.0,name=Apple TV 4K']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build and test
        run: swift test
        env:
          destination: ${{ matrix.destination }}
      - name: Code coverage
        run: curl -s https://codecov.io/bash
